ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,18 +1,44 @@
-name: my first pipeline
-on: push 
-
+name: My first pipeline
+on: push
 jobs:
+
   build:
     runs-on: ubuntu-latest
     steps:
-     - name: checkout code
-       uses: actions/checkout@v4
-     - name: build image
-       run: docker build -t ${{secrets.DOCKER_USERNAME}}/ci_portifolio .
-     - name: list log in
-       uses: docker/login-action@v4
-       with:
-         username: ${{ secrets.DOCKER_USERNAME }}
-         password: ${{ secrets.DOCKER_PASSWORD }}
-     - name: push image to registry
-       run: docker push${{secrets.DOCKER_USERNAME}}/ci_portifolio . 
+      - name: checkout code
+        uses: actions/checkout@v4 
+      - name: Build image
+        run: |
+         docker build -t ${{secrets.DOCKER_USERNAME}}/ciportofolio:${{github.run_number}} .
+         docker build -t ${{secrets.DOCKER_USERNAME}}/ciportofolio .
+      - name: Docker login
+        uses: docker/login-action@v4
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Push image to registry
+        run: |
+         docker push ${{secrets.DOCKER_USERNAME}}/ciportofolio:${{github.run_number}}
+         docker push ${{secrets.DOCKER_USERNAME}}/ciportofolio
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: SSh to Linux and run container
+        uses: appleboy/ssh-action@v1
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          key: ${{ secrets.PRIVATE_KEY }}
+          script: |
+              docker rm -f portfolio || echo " Container not found,skipping removal"
+              docker run -d --name portfolio -p 8080:80 ${{secrets.DOCKER_USERNAME}}/ciportofolio
+
+
+
+
+
+
+
+
